### PR TITLE
Split sounds into single knock

### PR DESCRIPTION
**Pull request by MokkaCicc**
I split your main sound files into several knock sound files, now punching a door make only one random knock.
I think this gives a better feeling.

### CODE REVIEW

**Comment by MokkaCicc** [comment]
If you accept this PR, just note that I forgot to change the mod version in the gradle.properties

**Comment by ZandercraftGames** [comment]
Hey @MokkaCicc! This change would also be very much welcome on the unofficial forge port of the mod. :D
https://github.com/ZandercraftGames/Door-Knocker-Forge

**Comment by MokkaCicc** [comment]
@ZandercraftGames I never touch a Forge mod in my life, I will maybe do it but this is not my top priority now. But since it's a fairly simple PR (split two sound files and modify a json file), I think you are capable to do it. You can reuse the split I made if you want to implemente this feature faster.

**Comment by ZandercraftGames** [comment]
> @ZandercraftGames I never touch a Forge mod in my life, I will maybe do it but this is not my top priority now. But since it's a fairly simple PR (split two sound files and modify a json file), I think you are capable to do it. You can reuse the split I made if you want to implemente this feature faster.

Oh, I'm definitely capable of doing it. The reason why I ask is so that you can get credit for your contribution by having your name on the commits. If you are fine with me just implementing it, that's fine as well.

**Comment by ZandercraftGames** [comment]
@MokkaCicc Feature has been added to the Forge port and credit has been given :D
https://github.com/ZandercraftGames/Door-Knocker-Forge/pull/2

**Comment by MokkaCicc** [comment]
@ZandercraftGames Sweet!

**Comment by froyo4u** [comment]
Merged

**Pull request merged**
